name: Test pull request
on: 
  pull_request:
    branches:
      - main


jobs:
  everything:
    name: Build, test and show code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Build container image
        run: |
          make build

      - name: Run tests and show code coverage
        run: |
          make coverage

